### ISSUE TITLE
Database error after 20.04.2 (broker > 20.04.2 crash)

### ISSUE THREAD

**Issue by BlackstormFirst** [centreon/centreon-broker#440]
Hello Centreon Team,

A recently tried to update my Centreon ISO 20.04.2 (CentOS 7, Centreon 20.04.2) to 20.04.4

The broker in lastest versions begin to log some errors into the next file:
/var/log/centreon-broker/central-broker-master.log

error: conflict_manager: error in the main loop: Data too long for the column 'value' at row 1 (while executing statement 991002983).

This error seems to be not critical for the loop, but i would like to correct it if possible.

The most important:
After the lastest updates (broker 20.04.5 and 20.04.6) we have a crash of the broker during the main loop with that error:

error: conflict_manager: error in the main loop: Incorrect string value: "\xE2\x95\xE2\..." for column `centreon_storage`.`services`.`output` at row 1 (while executing statement 1527054902).

Plugins stop working and the GUI have not refresh (i see only 40 checks against more than 1600).

I tried to clean all entries for output into the database manually, but after few seconds the loop crash again with the same error.
I also tried to clean the index reference of the deleted service but i had no luck.

I rollback my server to the 20.04.2... waiting for a new stable release.

An other thing, the error seems appear after a complete update (OS + centreon) and only after the reboot. (not confirmed).

Can someone can provide to me some help please ? or just confirm the issue and correct it for the next open release.

Best regards,

I can speak French if necessary or for more precisions.

**Comment by bouda1** [comment]
Hi @BlackstormFirst 
Could you send the exact plugin output when you execute it by hand?
Or put it into a file and join it here please?
Thank you.

**Comment by bouda1** [comment]
Another remark, when you have done your update of broker, you also had to update engine.
If you had some retention (memory, queue files), they could be badly encoded and hence give you suche errors.
So, the idea would be:
* update engine to the last version.
* keep it running for a while
* update broker that should well read utf-8 strings.

Regards.

**Comment by BlackstormFirst** [comment]
Hello @bouda1 
I'm currently out of my office, i will try to give you more informations tomorrow.
I'll add more debug info into my logs to find what plugins may send inappropriate data/values.

I'm using default Centreon Plugins pack, check_wmi_plus, nagios plugins pack and some personal plugins (mainly bash files).
Maybe the wmi plugins return some old characters from WinXp/2003 OS...

I hope i will be able to send you these info quickly ^^
Best regards,

**Comment by BlackstormFirst** [comment]
Hello,

I don't forgot you ^^ I didn't had time to get the specified logs.. and it's a quite difficult to revert to my snapshot with the production server without loosing the entire monitoring on my network during the debug time.

So i killed all snapshots, and i will retry a proper upgrade (1 - OS upgrade, 2 - Engine and UI upgrade, 3 - Broker and plugins upgrades.)

That time i will add "very detailed logs" to the broker configuration to see if a specific plugin become inappropriate with the new releases.

Sorry for delay :(
Best Regards,

**Comment by bouda1** [comment]
Hi,

You are not the only one to have such an issue.
What I have seen is that some checks return an output containing a string encoded with several encodings, utf-8 and ISO-8859 for example.
I should find time to work on this next week.
And if you can send me the exact output of a bad check, I will be able to test it with the new version :smiley: 

Don't worry for the delay.
Thanks, regards.

**Comment by BlackstormFirst** [comment]
So,
1 -After the first reboot, and only a system update with very detailed log, i find more information about my first issue (i am checking it), but a new error appear into this detailed log:
error: file '/etc/centreon-broker/log-config.json' does not exist.

I create it manually void.

The "Data too long for colum 'value'" come from the "centreon_cisco_standard_snmp.pl" plugin with the "environment" mode.
-> Could not store custom variable (name: EXTRAOPTIONS, host: xxx, service: xxxx)

I will try to recreate the plugins on the hosts to see if it fix it...

2 - Centreon web and Engine update :
Ok no issue after updating to UI 20.04.4 and Engine 20.04.4
Reboot

3 - Centreon Broker and Gorgone update
Juste after the update: OK
After a reboot: NOK

I toke a snapshot just before the broker and gorgone update, so i am reverting to the previous steep... i will let's the engine update all entries before to try a new time...

Best Regards,

**Comment by BlackstormFirst** [comment]
Ok, for the first one, my database have only a varchar(255) for the customvariables's 'value' field... i need to use at least 271 characters to filter the appropriate content (remove psu check, modify temp warning and critical...)

Is it possible to upgrade that value into the SQL sources please ? it's not a name or a label... it's a field for content, so you may have more than 255 characters into this type of fields... otherwise the default plugin should purpose more options to limit the content into only one variable.

N.B: If it worked before (or simply if you was able to set it), that means that value was decreased previously and probably recently.

I tried to alter the column to provide (default_value and value) a VARCHAR(500) -> Waiting for an official solution...

That seems to clean some old and duplicated group host data... no more error after that about the data length... (for the first issue) but not a normal way...

------> Also, after the Centreon Engine and UI Update, i see into the log "unexpected end of input" just after endpoint creation for "central-broker-master-perfdata".

I revert my state just after the engine update... waiting to create a new snapshot...

**Comment by BlackstormFirst** [comment]
> Hi @BlackstormFirst
> Could you send the exact plugin output when you execute it by hand?
> Or put it into a file and join it here please?
> Thank you.

Hi,
It's very difficult to export data from my private and restricted network, but this is the plugin command line for the "too long data" issue:

/usr/lib/centreon/plugins/centreon_cisco_standard_snmp.pl --plugin=network::cisco::standard::snmp::plugin --mode=environment --hostname=xxx.xxx.xxx.xxx --snmp-version='2c' --snmp-community='XXXXXXXXXXX' --component='.*' --verbose --filter-perfdata='^(sensor\.(celsius_|rpm_)|temp_)' --filter="psu,1010" --filter="psu,2010" --filter='psu,1001' --filter='psu,2001' --warning='sensor.celsus,.*,50' --warning='temperature,.*,50' --critical='sensor.celsus,.*,60' --critical='temperature,.*,60'

The value for "EXTRAOPTIONS" field should be:
--verbose --filter-perfdata='^(sensor\.(celsius_|rpm_)|temp_)' --filter="psu,1010" --filter="psu,2010" --filter='psu,1001' --filter='psu,2001' --warning='sensor.celsus,.*,50' --warning='temperature,.*,50' --critical='sensor.celsus,.*,60' --critical='temperature,.*,60'

Best regards,

**Comment by BlackstormFirst** [comment]
Hello,
I found several plugins with a corrupted display into the UI since this week-end.
The first come from a personal plugin that check the esxi snapshots using vmware cli into a bash file (accents are not correctly displayed), but it's not really critical...

In other hand, i find a WMIC plugin witch check a French Windows Eventlogs with accents and the rendering is clearly bad into the UI (or into the DB).

Best regards,

**Comment by bouda1** [comment]
If you also have an issue concerning security, you can replace your hostnames, services or whatever characters with some X. Just keep the bad characters, it will be suffisant for us to check the new upcoming patch.
Thanks.

**Comment by BlackstormFirst** [comment]
Hello,
I think the error come from the database (or it's a part of the problem).
Even my alias descriptions are affected into the UI, not only the returns from plugins.

Another things very very odd, is on one of my personal plugin, using wmic. When i execute the plugin manually, in command line, i have no issue (all field and content are correctly displayed into the console), but into the UI i only have the hardcoded text, the content of all variables are not displayed... (i specify that the content have no accent).

**Comment by bouda1** [comment]
About the column size to store text field. Since centreon 20.04, we try to
work with Mariadb in strict mode. One of the impacts is if you try to
insert a string of 300 characters in a column of max size 255 is:
* without strict mode : the string is cut and only the first 255 characters
are inserted => that was how Broker worked before.
* with strict mode: An error about the too long string is returned by the
database and the string won't be inserted.

So you can disable the strict mode if you have issues at the moment and
things will work as before.

In the last versions of Broker, we have implemented on almost all text
columns something to truncate the string as it was done before. This will
surely be improved in next releases but needs some reflection.

About the encoding, there is a last patch in the master branch of
centreon-engine that should fix your issue. There was still an issue in the
encoding check engine. Now we have to wait for this patch to be accepted by
the release management...

**Comment by BlackstormFirst** [comment]
Hello @bouda1 
Thanks for your feedback.

I will try these 2 fixes, I hope it will help.

If possible, i will post the confirmation here ^^

Best regards,

**Comment by BlackstormFirst** [comment]
Hello @bouda1 

First feedback with the new engine.

So, i download the sources, and install the engine over my existing installation.
The first hour was not very relevant, the charset error is still present and i only had 90 checks... but after the broker update and a run all over the night, i retrieve a lot of them.

In other hand, i still have an error in the log, some plugins are still empty or not checked (not a lot), i find the next error into the logs and one other important thing, since the broker update i loose all my "hosts group" (i can't filter with hostgroup anymore..)

the log error is: error: mysql; Error while sending prepared query: Incorrect string value: '\xE2\x95\xE2\x80\x9Dc...' for column `centreon_storage`.`services`.òutput` at row 1 (SQL: could not store service status (host: 130, service: XXXX) )

In addition this update don't seems to correct invalid character into the UI.

NB: I only update the engine from the sources, not the broker or another element. Should i also had used the broker sources ? or anything else ?

Best regards,

**Comment by BlackstormFirst** [comment]
Hello new update...
After restarting the server this morning, accents issue is gone from the UI (alias with accents are now correctly displayed and plugins' returns with accents are good too.)

So i still have an issue with a wmic plugin with the error above, but that time all references to this plugin disapear from checked services (the services by host still have this plugins enabled... but i losse 90% of checks from that template) and finally, my hostgroup filtering never back...

I will stay in this situation, waiting for another appropriate solution.

Have a nice day.
Best regards,

**Comment by BlackstormFirst** [comment]
Hi @bouda1 
Have you got some news about this issue please ?
Do i need to do something more ? or just wait for an official yum update ?

Thanks a lot.
Have a nice day.

**Comment by BlackstormFirst** [comment]
Hello @bouda1 
I tried the lastest broker and engine sources but that don't help...
I was forced to disable all my wmic plugins from French OS's, reload the config, stop the services, then cleanup all cached data to back in a functional state.

I cleaned;
- /tmp/
- /var/lib/centreon/status
- /var/lib/centreon/metrics
- /var/lib/centreon/centplugins

I hope the charset check will be more efficient with next releases/sources of the engine...
The data charset was good until these last releases and the console return correctly the right characters.

The culprit is clearly come from the engine.

Best regards,

**Comment by bouda1** [comment]
I'm sorry. The patch is ready for three weeks now. I have just come back
from holidays and realize it is not released yet.
Let's hope it will be soon.
Cheers.

**Comment by BlackstormFirst** [comment]
Hello @bouda1

Thanks for the feedback, i hope your holidays was calm and restful ;)

Can you publish the link to your pending commit please ? i will try the patch directly on my sources... the next yum release may take a long time to be published officially...

In otherhand, just for information, when i compile the engine and broker, i found 2 issues.

The first one with the Engine: After "make install" with all default options, the centengine init script go to the the init.d directory and if you already have a systemd init script the interface reload/restart a new process... so you have a centengine process started by systemd when you boot and another one with the init.d script when you restart the poller from the UI. --> Fix: remove the init.d script or explicitly add the systemd option into the c++ variable by default (maybe a check for the existing systemd env.)

The second one, is a little fix for the broker... into the cmake.sh script... you miss to replace the "cmake" command by the variable "$cmake" so cmake3 is never call and the script finish with error.

Best regards,

**Comment by bouda1** [comment]
Thanks for your feedback. If you want, you can even make a pull request!
Also, be careful when you install centreon-engine with 'make install', you
change read/write rights on the /etc/centreon-engine directory. And then
you won't be able to push your new configurations from the web interface.
Usually, I use a chown -R apache:apache /etc/centreon-engine

I think you can try engine and broker from the master branches.
Best regards.

**Comment by BlackstormFirst** [comment]
Hello @bouda1 
Last night i install the lastest engine sources with the new broker 20.04.7-1 from Yum update... not better...
I still have an issue with 2 of my WMIC plugins. The first one still won't display variables' content, the second send non utf8 characters (always with accents, the console can confirm^^) but the loop continuing to crash with the same error.

In the second case, bad characters should be retain (even if they can't be converted) and displayed as the console...

Actually, I cannot do any modifications with the UI (disable notifications for example... or enable/disable a service) until i clear all cached data (i think i also need to clear retention.dat and status.dat) to load the lastest UI seetings but that resend all notifications to everybody...).

I hope another fix will be available soon ^^

Best regards,
Have a nice day ;)

**Comment by bouda1** [comment]
If you could send me one of your WMIC output, it would be easier for me to
understand your issue. If some data are sensible, you can even change all
the ascii characters by an x for example.
Best regards.

**Comment by BlackstormFirst** [comment]
Hi,
I've uploaded an output for example (removed client ip), this is for our last case...
[test01.txt](https://github.com/centreon/centreon-broker/files/5034804/test01.txt)

**Comment by BlackstormFirst** [comment]
Here it's an example of the output from the wmic check with empty variables into the UI.
[test02.txt](https://github.com/centreon/centreon-broker/files/5034844/test02.txt)

As you can see, the file have the good content (numeric as been replaced by XX), open it into notepad++ the content seems to be UTF8 (on linux, chardetect define ASCII only ^^).

Best regards,

**Comment by BlackstormFirst** [comment]
Hello,

Thanks for your reply.
Ok, i understand for the services without metrics.

But for the loop, do you check the test01.txt file ? It have accents into this file (2nd line) and ambiguous characters... i have the next error when i run it:

error: mysql; Error while sending prepared query: Incorrect string value: '\xE2\x95\xE2\x80\x9Dc...' for column centreon_storage.services.òutput at row 1 (SQL: could not store service status (host: 130, service: 1901) )

**Comment by bouda1** [comment]
OK, I did not see this file. We will check them tomorrow.
Thanks again. Regards

**Comment by BlackstormFirst** [comment]
Hello,

This week we had a big issue due to the high temp in France.. Centreon is now completly unusable in the current state...

**Comment by bouda1** [comment]
The next master of engine/broker fix your issue with test01 and test02 files.

**Comment by BlackstormFirst** [comment]
Hi,

Thanks for the feedback again ^^ i had a hard week-end ^^
I will try both this night or tomorrow morning.

I will give you a confirmation about these fixes as soon as possible.
Best regards,

**Comment by BlackstormFirst** [comment]
Hello,
First feedback, we are apparently good for the accented and ambiguous characters, thanks a lot for the fix.
In other hand, the empty variables are still here... i will check on my side if the problem do not come from the file itself... or if i have altered it...

**Comment by BlackstormFirst** [comment]
For test02, still no content for variable even if i add a metric.

Best regards,

**Comment by bouda1** [comment]
I don't understand your issue on test02 file.
I have made a check that returns this output and get it as is. What
variable are you referring to?
Cheers.

**Comment by BlackstormFirst** [comment]
Hello,
The best way, is to try it yourself...

You can use: ./check_wmi_infos -h host_ip -u 'domain_user' -p 'password'

That should output the minimal informations...

You can add the '-e' option to have extended informations.. but in my case, actually the output is like my previous screenshot.

N.B: Be sure to have the wmic binary installed in /usr/bin/wmic ^^

[check_wmi_infos.zip](https://github.com/centreon/centreon-broker/files/5061957/check_wmi_infos.zip)

Have a nice day ^^

**Comment by lpinsivy** [comment]
Hi @BlackstormFirst 

When you perform test on shell terminal, do you used centreon-engine user to run your plugin?

**Comment by BlackstormFirst** [comment]
Hello,
yes, i always use the centreon-engine to run plugins ^^

Have you try  the plugin ? is the problem reproducible on your server ?

**Comment by lpinsivy** [comment]
I can't try the plugin because I didn't have access to a Windows administrator domain account.

What is the result in command line and what is the result in centreon_storage db ?

**Comment by BlackstormFirst** [comment]
That's really odd, when i check the DB, i have some time the good results into several colums but not for all and nothing is displayed into the Centreon GUI...

I will clear the cache again... to be sure, otherwise i will send you some screenshot.

Best regards,

**Comment by BlackstormFirst** [comment]
Hi,
I do not had the time today to clean the cache and retry. I hope tomorrow.

Best regards,

**Comment by BlackstormFirst** [comment]
Hello, i still had no times to recheck the content, but i find another impacted plugin.
That plugin use "snmpget -Onq" options and the GUI output return an error: -Onq: command not found.

It's like the check doesn't use the good interpreter.

What interpreter is used by centengine please ?
Can you remember me, directories i need to clean to cleanup the cache please ? (if possible without resend all notifications please) ?

thanks
best regards,

**Comment by BlackstormFirst** [comment]
Hello guys,
Thanks for your help.

I clearly didn't had times to recheck these plugins during last weeks so i am closing this tickets and i will post a new one if necessary after my cache purge and if the issue is still present.

Have a nice day.
Best regards.
